name: bnpool
channels:
  - pytorch
  - pyg
  - nvidia                    # comment this line out for CPU/MPS-only installation
  - conda-forge
  - defaults
dependencies:
  - numpy<2
  - python>=3.9
  - pytorch>=1.8
  - pytorch-cuda=12.1         # comment this line out for CPU/MPS-only installation
  - pyg>=2.6
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - lightning
  - scikit-learn
  - pip
  - pip:
      - hydra-core
      - omegaconf
      - ogb
      - tensorboard
      - pygsp
      - torch-geometric-pool
