defaults:
  - default
  - override dataset: community
  - override architecture: clustering
  - _self_

optimizer:
  hparams:
    lr: 5e-3

batch_size: 1
epochs: 10000

callbacks:
  patience: 300
  monitor: train_loss
  mode: min
