defaults:
  - run_classification
  - override hydra/sweeper: basic 
  - _self_

epochs: 2

hydra:
  sweeper:
    params:
      dataset: collab, colors, mutagenicity, NCI1, reddit-b, mutag, enzymes, proteins, molhiv, pep-s, multipartite, bench-hard, imdb-b, dd
      pooler: bnpool, mincut, diff, dmon, jb, graclus, ec, kmis, sep, eigen, topk
