defaults:
  - run_clustering
  - override hydra/sweeper: basic 
  - _self_

epochs: 2

hydra:
  sweeper:
    params:
      dataset: community, cora, dblp, citeseer, pubmed
      pooler: bnpool, mincut, diff, dmon, jb
