# @package _global_

dataset:
  family: TUDataset
  name: COLLAB
  hparams:
    seed: 777
    n_folds: 10
    fold_id: 0
    batch_size: 32
    transform: ['constant']
  callbacks:
    monitor: val_acc
    mode: max